export enum SocketEvents {

    CONNECT = "connect",
    CONNECT_ERROR = "connect_error",
    CONNECTION = "connection",
    DISCONECTION = "disconnecting",

    TASKBOARD = "taskboard",
    USER= "user",

    // Custom Events

    TASKBOARD_MEMBERS = "TASKBOARD_MEMBERS",

    JOIN_TASKBOARD = "JOIN_TASKBOARD",
    LEAVE_TASKBOARD = "LEAVE_TASKBOARD",
    JOINED_TASKBOARD = "JOINED_TASKBOARD",

    CARD_CREATED = "CARD_CREATED",
    CARD_UPDATED = "CARD_UPDATED",
    CARD_DELETED = "CARD_DELETED",
    CARD_MOVED = "CARD_MOVED",

    LIST_CREATED = "LIST_CREATED",
    LIST_UPDATED = "LIST_UPDATED",
    LIST_DELETED = "LIST_DELETED",
    LIST_MOVED = "LIST_MOVED",

    COMMENT_CREATED = "COMMENT_CREATED",
    COMMENT_UPDATED = "COMMENT_UPDATED",
    COMMENT_DELETED = "COMMENT_DELETED",

    TASKBOARD_DELETED = "TASKBOARD_DELETED",
    TASKBOARD_UPDATED = "TASKBOARD_UPDATED"

}
